#! /bin/bash

source myinclude

CDIR=""
cd $host_homedir

CDIR=$arch_dir
if [ ! -d "$CDIR" ]; then
    echo "making new directory of $CDIR"
    mkdir $CDIR
fi;
             
for f in `ls -F | grep "/"` ; do
   len=`expr ${#f} - 1`
   dir=${f:0:len}

   if [ `echo $NOUSER_LIST | grep -c "|"$dir"|"` = 0 ] ; then

      echo "dumping mysql db of $dir into archive ..." 
      mysqldump -uroot -p$mysql_pw  $dir'_db' > $CDIR/$dir-$(date +%y%m%d)_$(date +%H%M).dump
      cd $host_homedir/$dir
      echo "backng up with tar of $dir into archive..." `pwd`
      tar cfz $CDIR/$dir-$(date +%y%m%d)_$(date +%H%M).tgz public_html/* 

   else

     cd $host_homedir/$dir
     echo "backp system user with tgz of $dir into archive..." 
     tar cf $CDIR/$dir-$(date +%y%m%d)_$(date +%H%M).tgz .

   fi;
done

tar cfz $CDIR/mybin-$(date +%y%m%d)_$(date +%H%M).tgz /usr/local/mybin
