#!/bin/bash

source myinclude
mysql -hdbr-aurora.clhvwtdfc3ov.ap-northeast-2.rds.amazonaws.com -udbr_admin -pk99614791 
#mysql -u dbr-admin -p -h dbr-aurora.clhvwtdfc3ov.ap-northeast-2.rds.amazonaws.com
