#! /bin/bash

source /usr/local/pmt/mys3
source /usr/local/mybin/myinclude

#if /backup has file or dir, it doesn't mount s3 - pre-cleaning operation
#fusermount -u /backup ; sleep 1
#rm -rf /backup/*

#sudo /usr/lib/golang/bin/goofys $s3bucket /backup
source /usr/local/mybin/mymntback

cd $host_homedir

#if [ ! -d "$backdaily_dir" ]; then
#    echo "making new directory of $backdaily_dir"
#    mkdir $backdaily_dir
#fi;

mkdir -p $backdaily_dir 
mkdir -p $backmonthly_dir 
curr_day=$(date +%d)
            
for f in `ls -F | grep "/"` ; do
   len=`expr ${#f} - 1`
   dir=${f:0:len}
 
   filename=$dir-$(date +%y%m%d)

   if [ `echo $NOUSER_LIST | grep -c "|"$dir"|"` = 0 ] ; then

      echo "" 
      echo "dumping mysql db of $dir into archive ..." 

      TARGET_DB=$dir'_db'
      source /usr/local/pmt/myinclude

      mysqldump -h$my_endpoint -u$my_admin_user -p$mysql_pw $dir'_db' > $backdaily_dir/$filename.sql
      #mysqldump -uroot -p$mysql_pw  $dir'_db' > $backdaily_dir/$filename.sql


      cd $host_homedir/$dir
      echo "backng up with tar of $dir into archive..." `pwd`
      tar czf $backdaily_dir/$filename.tar.gz public_html/* 
      gzip -f $backdaily_dir/$filename.sql
      
      if [ "$curr_day" = "01" ] ; then
        cp $backdaily_dir/$filename.sql.gz $backmonthly_dir
        cp $backdaily_dir/$filename.tar.gz $backmonthly_dir
      fi

   else

     cd $host_homedir/$dir
     echo "backp system user with tgz of $dir into archive..." 
     tar czf /$backdaily_dir/$filename.tar.gz  public_html/* 

     if [ "$curr_day" = "01" ] ; then
        cp $backdaily_dir/$filename.tar.gz $backmonthly_dir
     fi

   fi;
done

tar cfz $backdaily_dir/mybin-$(date +%y%m%d).tgz /usr/local/mybin

for i in {0..6}; do ((keep[$(date +%Y%m%d -d "-$i day")]++)); done
#echo ${!keep[@]}
weekeep=${!keep[@]}

cd $backdaily_dir 

for backfile in ./*
do
  #echo "$backfile"
  backday=$(echo $backfile| cut -d"-" -f 2 | cut -d"." -f 1)
  #echo $backday

  if [[ $weekeep != *$backday* ]]; then
    echo $backfile" will be deleted !"
    rm -f $backfile
  fi;
done

for i in {0..11}; 
do
  date_buf=$(date +%Y%m%d -d "-$i month")
  date_buf=${date_buf:0:6}
  date_buf=$date_buf"01"
  ((monthly_keep[$date_buf]++));
done
#echo ${!monthly_keep[@]}
monthkeep=${!monthly_keep[@]}

cd $backmonthly_dir 

for monthly_backfile in ./*
do
  #echo "$monthly_backfile"
  backday=$(echo $monthly_backfile| cut -d"-" -f 2 | cut -d"." -f 1)
  #echo $backday

  if [[ $monthkeep != *$backday* ]]; then
    echo $monthly_backfile" will be deleted !"
    rm -f $monthly_backfile
  fi;
done

cd /
fusermount -u /backup
