#!/bin/bash

source myinclude
mkdir -p $host_homedir/$1/backups
mysqldump -hdbr-aurora.clhvwtdfc3ov.ap-northeast-2.rds.amazonaws.com -udbr_admin -pk99614791 "$1_db" > $host_homedir"/$1/backups/$1-$(date +%y%m%d)_$(date +%H%M).sql"

chown -R  $1  $host_homedir"/$1/backups/"
chgrp -R  apache  $host_homedir"/$1/backups/"
