#!/bin/bash
source myinclude

public_dir=$host_homedir/$1/public_html
uploads_dir=$host_homedir/$1/public_html/wp-content/uploads
kcp_pp_cli_file=$host_homedir/$1/public_html/wp-content/plugins/woosym-korean-localization/includes/lib/homekcp/bin/pp_cli

chown -R root $public_dir/
chgrp -R root $public_dir/

find $public_dir/ -type d -exec chmod 555 {} +
find $public_dir/ -type f -exec chmod 444 {} +
#chmod 555 $(find $public_dir/ -type d)
#chmod 444 $(find $public_dir/ -type f)

chown -R $1 $uploads_dir/
chgrp -R apache $uploads_dir/

find $uploads_dir/ -type d -exec chmod 775 {} +
find $uploads_dir/ -type f -exec chmod 664 {} +

#find $uploads_dir/ -type d -exec chmod 755 {} +
#find $uploads_dir/ -type f -exec chmod 644 {} +

if [ -f "$kcp_pp_cli_file" ]; then
  chmod 755 $kcp_pp_cli_file
fi

#chmod 755 $(find $uploads_dir/ -type d)
#chmod 644 $(find $uploads_dir/ -type f)
