#!/bin/bash
source myinclude

kcp_pp_cli_file=$public_dir/wp-content/plugins/woosym-korean-localization/includes/lib/homekcp/bin/pp_cli
kcp_pp_cli_file_sj=$public_dir/wp-content/plugins/woocommerce-kcp-kr/bin/pp_cli  # sangjugotgam
kcp_pp_cli_file_bb=$public_dir/wp-content/plugins/ibnet-kcp/kcp/bin/pp_cli  $bbulmedia

cache_dir=$public_dir/wp-content/plugins/special-recent-posts-2.4.7/cache # for sungduk
cache_dir_dm=$public_dir/wp-content/plugins/download-manager/cache # for download manager
cache_dir_fg=$public_dir/wp-content/plugins/radykal-fancy-gallery/admin/cache # for fancy gallery
upload_dir_fg=$public_dir/wp-content/fancygallery # for uploaddir 

#echo $public_dir

chown -R root $public_dir/
chgrp -R root $public_dir/

find $public_dir/ -type d -exec chmod 555 {} +
find $public_dir/ -type f -exec chmod 444 {} +

#chmod 555 $(find $public_dir/ -type d)
#chmod 444 $(find $public_dir/ -type f)

#echo $uploads_dir
chown -R $1 $uploads_dir/
chgrp -R apache $uploads_dir/

find $uploads_dir/ -type d -exec chmod 755 {} +
find $uploads_dir/ -type f -exec chmod 644 {} +

if [ -f "$kcp_pp_cli_file" ]; then
  chmod 755 $kcp_pp_cli_file
fi

if [ -f "$kcp_pp_cli_file_sj" ]; then
  chmod 755 $kcp_pp_cli_file_sj
fi

if [ -f "$kcp_pp_cli_file_bb" ]; then
  chmod 755 $kcp_pp_cli_file_bb
fi

if [ -d "$cache_dir" ]; then # for sungduk
  chown -R $1 $cache_dir
  chgrp -R apache $cache_dir
  chmod 755 $cache_dir
  chmod 644 $cache_dir/*
fi


if [ -d "$cache_dir_dm" ]; then # for download manager
  chown -R $1 $cache_dir_dm
  chgrp -R apache $cache_dir_dm
  chmod 755 $cache_dir_dm
  chmod 644 $cache_dir_dm/*
fi

if [ -d "$cache_dir_fg" ]; then # for fancy-gallery
  chown -R $1 $cache_dir_fg
  chgrp -R apache $cache_dir_fg
  chmod 755 $cache_dir_fg
  chmod 644 $cache_dir_fg/*
fi

if [ -d "$upload_dir_fg" ]; then # for fancy-gallery upload
  chown -R $1 $upload_dir_fg
  chgrp -R apache $upload_dir_fg
  find $upload_dir_fg/ -type d -exec chmod 755 {} +
  find $upload_dir_fg/ -type f -exec chmod 644 {} +
fi


#chmod 755 $(find $uploads_dir/ -type d)
#chmod 644 $(find $uploads_dir/ -type f)
