#!/bin/bash

source myinclude
cd $host_homedir/$1
mkdir -p $host_homedir/$1/backups
tar cfh $host_homedir"/$1/backups/$1.tar"  "public_html" 

#chown -R  $1  $host_homedir"/$1/backups/"
#chgrp -R  apache  $host_homedir"/$1/backups/"
