#!/bin/bash
source myinclude

#echo $public_dir
wskl="woosym-korean-localization"
wskl_dir=$public_dir/wp-content/plugins/$wskl
wp_content_dir=$public_dir/wp-content
wp_plugins_dir=$wp_content_dir/plugins

if [ -d "$wskl_dir" ]; then
  mv $wskl_dir $wp_content_dir/$wskl-$(date +%y%m%d)_$(date +%H%M)
fi

#echo $wskl_dir
cp -r  $common_dir/$wskl $wp_plugins_dir/
chown -R  $1  $wskl_dir
chgrp -R  apache $wskl_dir

