#! /bin/bash

source myinclude

CDIR=""
cd $host_homedir
for f in `ls -F | grep "/"` ; do
   len=`expr ${#f} - 1`
   dir=${f:0:len}

   if [ "$dir" != "admin" ] && [ "$dir" != "archive" ] && [ "$dir" != "centos" ] && [ "$dir" != "http" ] && [ "$dir" != "kloxo" ] && [ "$dir" != "lxadmin" ] && [ "$dir" != "nouser" ] && [ "$dir" != "php-fpm" ] && [ "$dir" != "phpini" ] && [ "$dir" != "srdbm" ] && [ "$dir" != "vpopmail" ] && [ "$dir" != "woosym-korean-localization" ] ; then
 
      CDIR=$arch_dir
      if [ ! -d "$CDIR" ]; then
          echo "making new directory of $CDIR"
          mkdir $CDIR
      fi;
             
      echo "dump mysql db of $dir into archive ..." 
      mysqldump -uroot -p$mysql_pw  $dir'_db' > $CDIR/$dir-$(date +%y%m%d)_$(date +%H%M).dump
      cd $host_homedir/$dir
      echo "backp with tar of $dir into archive..." `pwd`
      tar cf $CDIR/$dir-$(date +%y%m%d)_$(date +%H%M).tar public_html/* 

      echo $CDIR/$dir-$(date +%y%m%d)_$(date +%H%M).tar "<-" $host_homedir/$dir
	
   #else

   #   cd $host_homedir/$dir
   #   echo "backp system user with tar of $dir into archive..." 
   #   tar cf $CDIR/$dir-$(date +%y%m%d)_$(date +%H%M).tar .

   fi;
done
cp -a /usr/local/mybin $arch_dir/usrlocalbin
