#!/bin/bash
cd /var/zpanel/hostdata
for f in `ls -F | grep "/"` ; do
   #echo "$f" | cut -b 1-3 
   #echo ${f:1:5}
   #len=`expr ${#f} - 1`
   #echo ${f/\//} `expr ${#f} - 1`
   len=`expr ${#f} - 1`
   dir=${f:0:len}
   if [ "$dir" != "zadmin" ] && [ "$dir" != "wp381.org" ]; then 
      echo "dump mysql db of $dir ..." 
      mydump $dir
      echo "backp with tar of $dir ..." 
      mytar $dir
   fi;
done

