#!/bin/bash

source myinclude
mkdir -p $host_homedir/$1/backups
mysqldump -uroot -p$mysql_pw  "$1_db" > $host_homedir"/$1/backups/$1.sql"

#chown -R  $1  $host_homedir"/$1/backups/"
#chgrp -R  apache  $host_homedir"/$1/backups/"
