#!/bin/bash

source myinclude

if [ "$1" = "1" ]; then
   srv_ip=$ip1
elif [ "$1" = "2" ]; then
   srv_ip=$ip2
elif [ "$1" = "3" ]; then
   srv_ip=$ip3
fi

scp -P $scp_port -i $mybin_dir/$pem_file $ip_user@$srv_ip:$2 $3
